// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: agent/proto/grpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Loacaladdr string `protobuf:"bytes,2,opt,name=Loacaladdr,proto3" json:"Loacaladdr,omitempty"`
	Status     int32  `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Agent) Reset() {
	*x = Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_agent_proto_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Agent) GetLoacaladdr() string {
	if x != nil {
		return x.Loacaladdr
	}
	return ""
}

func (x *Agent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Expression string `protobuf:"bytes,2,opt,name=Expression,proto3" json:"Expression,omitempty"`
	ValidExp   bool   `protobuf:"varint,3,opt,name=ValidExp,proto3" json:"ValidExp,omitempty"`
	Time       int32  `protobuf:"varint,4,opt,name=Time,proto3" json:"Time,omitempty"`
	Status     int32  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Result     int64  `protobuf:"varint,6,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_agent_proto_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Task) GetValidExp() bool {
	if x != nil {
		return x.ValidExp
	}
	return false
}

func (x *Task) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Task) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Task) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type TimeLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plus  int32 `protobuf:"varint,1,opt,name=Plus,proto3" json:"Plus,omitempty"`
	Minus int32 `protobuf:"varint,2,opt,name=Minus,proto3" json:"Minus,omitempty"`
	Mul   int32 `protobuf:"varint,3,opt,name=Mul,proto3" json:"Mul,omitempty"`
	Div   int32 `protobuf:"varint,4,opt,name=Div,proto3" json:"Div,omitempty"`
	All   int32 `protobuf:"varint,5,opt,name=All,proto3" json:"All,omitempty"`
}

func (x *TimeLimit) Reset() {
	*x = TimeLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeLimit) ProtoMessage() {}

func (x *TimeLimit) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeLimit.ProtoReflect.Descriptor instead.
func (*TimeLimit) Descriptor() ([]byte, []int) {
	return file_agent_proto_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *TimeLimit) GetPlus() int32 {
	if x != nil {
		return x.Plus
	}
	return 0
}

func (x *TimeLimit) GetMinus() int32 {
	if x != nil {
		return x.Minus
	}
	return 0
}

func (x *TimeLimit) GetMul() int32 {
	if x != nil {
		return x.Mul
	}
	return 0
}

func (x *TimeLimit) GetDiv() int32 {
	if x != nil {
		return x.Div
	}
	return 0
}

func (x *TimeLimit) GetAll() int32 {
	if x != nil {
		return x.All
	}
	return 0
}

type Zero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Zero) Reset() {
	*x = Zero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Zero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zero) ProtoMessage() {}

func (x *Zero) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zero.ProtoReflect.Descriptor instead.
func (*Zero) Descriptor() ([]byte, []int) {
	return file_agent_proto_grpc_proto_rawDescGZIP(), []int{3}
}

var File_agent_proto_grpc_proto protoreflect.FileDescriptor

var file_agent_proto_grpc_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x72, 0x76, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4c,
	0x6f, 0x61, 0x63, 0x61, 0x6c, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x4c, 0x6f, 0x61, 0x63, 0x61, 0x6c, 0x61, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x45, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x45, 0x78, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6b, 0x0a, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6c, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6c, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x69,
	0x6e, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x75, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x4d, 0x75, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x69, 0x76, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x44, 0x69, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x6c, 0x6c, 0x22, 0x06, 0x0a, 0x04, 0x5a, 0x65, 0x72,
	0x6f, 0x32, 0xf8, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x67, 0x65, 0x12, 0x2c, 0x0a,
	0x09, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x73, 0x72, 0x76,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x2e, 0x73, 0x72,
	0x76, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x5a, 0x65, 0x72, 0x6f, 0x12, 0x2a, 0x0a, 0x07, 0x48,
	0x65, 0x72, 0x74, 0x42, 0x69, 0x74, 0x12, 0x0f, 0x2e, 0x73, 0x72, 0x76, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x2e, 0x73, 0x72, 0x76, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x5a, 0x65, 0x72, 0x6f, 0x12, 0x2d, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x54,
	0x6f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x2e, 0x73, 0x72, 0x76, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0e, 0x2e, 0x73, 0x72, 0x76, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x5a, 0x65, 0x72, 0x6f, 0x12, 0x36, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x13, 0x2e, 0x73, 0x72, 0x76, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x1a, 0x0e,
	0x2e, 0x73, 0x72, 0x76, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x5a, 0x65, 0x72, 0x6f, 0x12, 0x2c,
	0x0a, 0x0a, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x2e, 0x73,
	0x72, 0x76, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0e, 0x2e, 0x73,
	0x72, 0x76, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x5a, 0x65, 0x72, 0x6f, 0x42, 0x13, 0x5a, 0x11,
	0x6c, 0x61, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_proto_grpc_proto_rawDescOnce sync.Once
	file_agent_proto_grpc_proto_rawDescData = file_agent_proto_grpc_proto_rawDesc
)

func file_agent_proto_grpc_proto_rawDescGZIP() []byte {
	file_agent_proto_grpc_proto_rawDescOnce.Do(func() {
		file_agent_proto_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_proto_grpc_proto_rawDescData)
	})
	return file_agent_proto_grpc_proto_rawDescData
}

var file_agent_proto_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_proto_grpc_proto_goTypes = []interface{}{
	(*Agent)(nil),     // 0: srvproto.Agent
	(*Task)(nil),      // 1: srvproto.Task
	(*TimeLimit)(nil), // 2: srvproto.TimeLimit
	(*Zero)(nil),      // 3: srvproto.Zero
}
var file_agent_proto_grpc_proto_depIdxs = []int32{
	0, // 0: srvproto.Messege.TaskAgent:input_type -> srvproto.Agent
	0, // 1: srvproto.Messege.HertBit:input_type -> srvproto.Agent
	1, // 2: srvproto.Messege.TaskToAgent:input_type -> srvproto.Task
	2, // 3: srvproto.Messege.UpdateTimeLimit:input_type -> srvproto.TimeLimit
	1, // 4: srvproto.Messege.AnswerTask:input_type -> srvproto.Task
	3, // 5: srvproto.Messege.TaskAgent:output_type -> srvproto.Zero
	3, // 6: srvproto.Messege.HertBit:output_type -> srvproto.Zero
	3, // 7: srvproto.Messege.TaskToAgent:output_type -> srvproto.Zero
	3, // 8: srvproto.Messege.UpdateTimeLimit:output_type -> srvproto.Zero
	3, // 9: srvproto.Messege.AnswerTask:output_type -> srvproto.Zero
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_proto_grpc_proto_init() }
func file_agent_proto_grpc_proto_init() {
	if File_agent_proto_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_proto_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Zero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_proto_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_grpc_proto_goTypes,
		DependencyIndexes: file_agent_proto_grpc_proto_depIdxs,
		MessageInfos:      file_agent_proto_grpc_proto_msgTypes,
	}.Build()
	File_agent_proto_grpc_proto = out.File
	file_agent_proto_grpc_proto_rawDesc = nil
	file_agent_proto_grpc_proto_goTypes = nil
	file_agent_proto_grpc_proto_depIdxs = nil
}
